-- Color Themes --

return {
	{ "catppuccin/nvim", lazy = true },
	{ "ellisonleao/gruvbox.nvim", lazy = true },
	{ "folke/tokyonight.nvim", lazy = true },
	{ "rose-pine/neovim", name = "rose-pine", lazy = true },
	{ "EdenEast/nightfox.nvim", lazy = true },
	{ "rebelot/kanagawa.nvim", lazy = true },
	{ "navarasu/onedark.nvim", lazy = true },
	{ "projekt0n/github-nvim-theme", lazy = true },
	{ "sainnhe/everforest", lazy = true },
	{ "marko-cerovac/material.nvim", lazy = true },
	{ "sainnhe/sonokai", lazy = true },
	{ "sainnhe/edge", lazy = true },
	{ "shaunsingh/nord.nvim", lazy = true },
	{ "Mofiqul/dracula.nvim", lazy = true },
	{ "tiagovla/tokyodark.nvim", lazy = true },
	{ "bluz71/vim-nightfly-colors", lazy = true },
	{ "bluz71/vim-moonfly-colors", lazy = true },
	{ "nyoom-engineering/oxocarbon.nvim", lazy = true },
	{ "savq/melange-nvim", lazy = true },
	{ "raphamorim/lucario", lazy = true },
	{ "ayu-theme/ayu-vim", lazy = true },
	{ "olimorris/onedarkpro.nvim", lazy = true },
	{ "phha/zenburn.nvim", lazy = true },
	{ "rafamadriz/neon", lazy = true },
	{ "rockerBOO/boo-colorscheme-nvim", lazy = true },
	{ "sekke276/dark_flat.nvim", lazy = true },
	{ "dasupradyumna/midnight.nvim", lazy = false, priority = 1000 },
	{ "rmehri01/onenord.nvim", lazy = true },
}
